feat: Parking Permits - Create Verint Case
smbc-digital/parking-enforcement-service pull request #19
Opened 2022-03-03 09:50 UTC by michaellau-smbc

Jira Card - Parking Permits - Build Form 1 (DIGITAL-7910)

-) Add new esl.json datasource for parking permit 
-) Update Property in EligibleStreet class so house number is a list<string> and visitior is a nullable integer
-) Update Parking permit model 
-) Update Parking Permit service to create verint case
-) Update email helper to send Parking Permit email
-) Add Parking permit helper to extract methods from service
-) Add HttpResponseExceptionFilter
-) Refactor- Extract Options class, usings, spaces
-) Add unit test for parking permit 

Checklist
- [x] Code compiles correctly
- [x] Created tests for the new changes
- [x] All tests passing
- [ ] Extended the README / documentation, if necessary

2022-03-03 09:54 UTC, lydiagray commented on src/Controllers/ParkingPermitsController.cs
>          [Route("checkEligibleAddress")]
Routes should be kebab case

2022-03-03 09:55 UTC, lydiagray commented on src/Controllers/ParkingPermitsController.cs
>          [Route("getPermitInformation")]
Routes should be kebab case

2022-03-03 10:17 UTC, lydiagray commented on src/Helpers/MailHelper.cs
> +                };
Just looks a bit weird, either move the closing brace up a line, or move the string to a line between the braces

2022-03-03 10:20 UTC, lydiagray commented on src/Helpers/PermitHelper.cs
> +            if (eligibleStreet.Area == PermitConstants.DUPLICATE)
Change to .Equals( )

2022-03-03 10:20 UTC, lydiagray commented on src/Helpers/PermitHelper.cs
> +                return System.Text.Json.JsonSerializer.Serialize(duplicationList);
Can we import System.Text.Json so that you only need JsonSerlializer.Serialize here?

2022-03-03 10:21 UTC, lydiagray commented on src/Helpers/PermitHelper.cs
> +            var duplicate = eligibleStreets.Count(address => address.USRN == verintAddress.USRN && address.POSTCODE.ToLower().Contains(address.POSTCODE.ToLower()));
Change == to .Equals( )

2022-03-03 10:21 UTC, lydiagray commented on src/Helpers/PermitHelper.cs
> +            var address = eligibleStreets.FirstOrDefault(address => address.USRN == verintAddress.USRN && address.POSTCODE.ToLower().Contains(verintAddress.Postcode.ToLower()));
Change == to .Equals( )

2022-03-03 10:21 UTC, lydiagray commented on src/Helpers/PermitHelper.cs
> +                        if (number == verintAddress.Number)
Change == to .Equals( )

2022-03-03 10:23 UTC, lydiagray commented on src/Interfaces/IMailHelper.cs
> +namespace parking_enforcement_service.Interfaces
When did we start having a single folder for all Interfaces?

2022-03-03 10:25 UTC, lydiagray commented on src/Interfaces/IPermitHelper.cs
> +        Task<EligibleStreets> GetAddressDetails(string yourAddress);
Spacing needs to be consistent

2022-03-03 10:26 UTC, lydiagray commented on src/Models/HttpResponseException.cs
> +    public class HttpResponseException : Exception
This now exists in the Models package so you can import it from there

2022-03-03 10:27 UTC, lydiagray commented on src/Models/ParkingPermitsRequest.cs
> +                {
Remove brackets if single line if

2022-03-03 10:28 UTC, lydiagray commented on src/Properties/launchSettings.json
> +        "ASPNETCORE_ENVIRONMENT": "int"
Should we be leaving this as local?

2022-03-03 10:30 UTC, lydiagray commented on src/Helpers/PermitHelper.cs
> +        public Case PermitRequestToVerintCase(ParkingPermitsRequest request)
Methods should start with a verb

2022-03-03 10:31 UTC, lydiagray commented on src/Services/ParkingPermitsService.cs
> +                throw new Exception($"ParkingEnforcementService::AddNoteWithAttachments, an exception has occured while adding note with attachment to case: {response.ResponseContent}", ex);
spelling mistake in occurred

2022-03-03 10:31 UTC, lydiagray commented on src/Services/ParkingPermitsService.cs
> +            if (eligibleStreet.Area == PermitConstants.DUPLICATE)
Change == to .Equals( )

2022-03-03 10:32 UTC, lydiagray commented on src/Services/ParkingPermitsService.cs
> +            return System.Text.Json.JsonSerializer.Serialize(permitList);
Can we import the System.Text.Json as a using?

2022-03-03 10:33 UTC, lydiagray commented on src/Services/ParkingPermitsService.cs
> +                var costText = eligibleStreets.Chargeable.ToLower() == "n" ? "This permit is <strong>free</strong>" : "This permit costs <strong>£41.50</strong>";
Change == to .Equals( )

2022-03-03 10:37 UTC, lydiagray commented on tests/Helpers/MailHelperTests.cs
> +            var callback = new Mail();
No // Arrange // Act // Assert

2022-03-03 10:37 UTC, lydiagray commented on tests/Helpers/MailHelperTests.cs
> +            Assert.Equal(EMailTemplate.GenericHtmlReport, callback.Template);
These should be separate tests

2022-03-03 10:38 UTC, lydiagray commented on tests/Helpers/MailHelperTests.cs
> +            Assert.Equal("We've received your application", callbackModel.Subject);
These should be separate tests

2022-03-03 10:38 UTC, lydiagray commented on tests/Helpers/PermitHelperTests.cs
> +        private Mock<IVerintServiceGateway> _mockVerintServiceGateway = new Mock<IVerintServiceGateway>();
Can be readonly

2022-03-03 10:39 UTC, lydiagray commented on tests/Helpers/PermitHelperTests.cs
> +        public async Task GetAddressDetails_ShouldTCallVerintGateway_GetPropertyByUprn()
A wild T appeared between Should and Call

2022-03-03 10:42 UTC, lydiagray commented on tests/Services/ParkingEnforcementServiceTests.cs
> +
// Arrange

2022-03-03 10:43 UTC, lydiagray commented on tests/Services/ParkingEnforcementServiceTests.cs
> -
// Arrange // Act // Assert

2022-03-03 10:46 UTC, lydiagray commented on tests/Services/ParkingPermitsServiceTests.cs
> +        private ParkingPermitsService _service;
Readonly

2022-03-03 10:47 UTC, lydiagray commented on tests/Services/ParkingPermitsServiceTests.cs
> +            // Assert
You can put both on the same line here, // Act & Assert

2022-03-03 10:55 UTC, lydiagray commented on tests/Services/ParkingPermitsServiceTests.cs
> +        private readonly ParkingPermitsRequest request = new ParkingPermitsRequest
request should be _request as it's private

2022-03-03 10:55 UTC, lydiagray commented on tests/Services/ParkingPermitsServiceTests.cs
> +            .ReturnsAsync(new HttpResponse<string>() { IsSuccessStatusCode = false });
Indenting

2022-03-03 10:57 UTC, lydiagray commented on tests/Services/ParkingPermitsServiceTests.cs
> +
No tests for an exception for AddNotesWithAttachments in CreateCase

2022-03-03 10:59 UTC, lydiagray commented on tests/Services/ParkingPermitsServiceTests.cs
> +        }
Needs some tests for the if's in the method

2022-03-03 11:00 UTC, lydiagray commented on src/Services/ParkingPermitsService.cs
> +                    new Option() { Text = "Duplication", Value = "Duplication", ConditionalElementId = "Duplication" }
Doesn't need the ( )

2022-03-03 11:01 UTC, lydiagray commented on src/Services/ParkingPermitsService.cs
>              }
Final else isn't needed, just return string.Empty

2022-03-03 11:05 UTC, lydiagray requested changes

2022-03-03 11:05 UTC, lydiagray commented on src/Helpers/PermitHelper.cs
> +            var address = new Address()
Don't need the ( )

2022-03-03 11:05 UTC, lydiagray commented on src/Helpers/PermitHelper.cs
> +            var options = new List<Option>()
Doesn't need the ( )

2022-03-03 11:05 UTC, lydiagray commented on tests/Helpers/PermitHelperTests.cs
> +}
No tests for any of the logic

2022-03-03 12:41 UTC, michaellau-smbc commented on src/Controllers/ParkingPermitsController.cs
>          [Route("checkEligibleAddress")]
Are you saying 'Post' need to be 'post?'

2022-03-03 15:32 UTC, lydiagray commented on src/Controllers/ParkingPermitsController.cs
>          [Route("checkEligibleAddress")]
The route needs to be "check-eligible-address"

2022-03-04 08:21 UTC, michaellau-smbc commented on src/Controllers/ParkingPermitsController.cs
>          [Route("checkEligibleAddress")]
Nice, did that yesterday

2022-03-04 10:41 UTC, lydiagray requested changes

2022-03-04 10:41 UTC, lydiagray commented on tests/Helpers/PermitHelperTests.cs
> +}
Still no testing of any of the if's

2022-03-04 10:41 UTC, lydiagray commented on tests/parking_enforcement_service_tests.csproj
> +    <PackageReference Include="StockportGovUK.NetStandard.Models" Version="3.16.0" />
Models is included in Gateways, you don't need it as a separate package

2022-03-04 10:41 UTC, lydiagray commented on src/parking_enforcement_service.csproj
> +    <PackageReference Include="StockportGovUK.NetStandard.Models" Version="3.16.0" />
Models is included in Gateways, you don't need a separate package

2022-03-04 11:32 UTC, michaellau-smbc commented on tests/Helpers/PermitHelperTests.cs
> +}
The logic tests are within the ParkingPermitServiceTests

2022-03-04 11:42 UTC, lydiagray commented on tests/Helpers/PermitHelperTests.cs
> +}
If the code is in the PermitHelper then the tests should be here not in the Service Tests

2022-03-07 11:59 UTC, lydiagray commented on tests/Helpers/PermitHelperTests.cs
> +        }
Could we get a test for GetAddressDetails for the Exception thown if the GetPropertyByUprn request is unsuccessful or null?

2022-03-07 11:59 UTC, lydiagray commented on src/Helpers/PermitHelper/PermitHelper.cs
> +
Empty line
Also, I think you could move this outside of the Chargeable if and only have it once - if I'm reading it correctly you add a new visitor permit to the list regardless of whether it's chargeable or not so you could have this? 

``` 
var options = new List<Option>
            {
                new Option
                {
                    Text = PermitConstants.NEW_RESIDENT_PERMIT_TEXT,
                    Value = PermitConstants.NEW_RESIDENT_PERMIT_VALUE
                }
            };

            if (eligibleStreet.Chargeable.ToLower().Equals("y"))
            {
                options.Add(new Option { Text = PermitConstants.RENEW_RESIDENT_PERMIT_TEXT, Value = PermitConstants.RENEW_RESIDENT_PERMIT_VALUE });

                if (eligibleStreet.Visitors > 0)
                    options.Add(new Option { Text = PermitConstants.RENEW_VISITOR_PERMIT_TEXT, Value = PermitConstants.RENEW_VISITOR_PERMIT_VALUE });
            }

            if (eligibleStreet.Visitors > 0)
                options.Add(new Option { Text = PermitConstants.NEW_VISITOR_PERMIT_TEXT, Value = PermitConstants.NEW_VISITOR_PERMIT_VALUE });

            return options.OrderBy(o => o.Text).ToList();

2022-03-07 11:59 UTC, lydiagray commented on src/Helpers/PermitHelper/PermitHelper.cs
> +            return options.OrderBy(o => o.Text).ToList(); ;
Extra semi-colon at the end

2022-03-07 11:59 UTC, lydiagray commented on src/Helpers/PermitHelper/PermitHelper.cs
> +        {
There are no unit tests for this

2022-03-07 11:59 UTC, lydiagray commented on src/Services/ParkingPermit/ParkingPermitsService.cs
> +        public async Task<string> CheckEligibleAddress(string yourAddress)
This method is in the Helper and this one is not used so needs removing along with the unit tests

2022-03-07 11:59 UTC, lydiagray commented on src/Services/ParkingPermit/ParkingPermitsService.cs
> +namespace parking_enforcement_service.Services
Add .ParkingPermit to the end of the namespace

2022-03-07 11:59 UTC, lydiagray commented on src/Services/ParkingPermit/ParkingPermitsService.cs
> +        private readonly ILogger<ParkingPermitsService> _logger;
Logger doesn't seem to be used so can it be removed?

2022-03-07 11:59 UTC, lydiagray commented on src/Helpers/PermitHelper/PermitHelper.cs
> +                    new Option() { Text = "Duplication", Value = "Duplication", ConditionalElementId = "Duplication" }
Remove the ( )

2022-03-07 11:59 UTC, lydiagray commented on tests/Services/ParkingPermitsServiceTests.cs
> +            // Arrange
// Act not // Arrange

2022-03-07 11:59 UTC, lydiagray commented on tests/Services/ParkingPermitsServiceTests.cs
> +            // Arrange
Duplicate line

2022-03-07 14:25 UTC, michaellau-smbc commented on src/Helpers/PermitHelper/PermitHelper.cs
> +            var duplicate = eligibleStreets.Count(address => !string.IsNullOrEmpty(address.USRN) && address.USRN.Equals(verintAddress.USRN) &&
Don't mind changing it but not to numberOfEligibleStreets. This variable is to catcher address that exist more than once in the data source. maybe call 'numberOfEligibleStreetDuplicated'

2022-03-07 15:41 UTC, lydiagray requested changes

2022-03-07 15:41 UTC, lydiagray commented on src/Models/EligibleStreets.cs
> +    public class EligibleStreets
Sorry >< can this be singular as it's a model for a single street

2022-03-08 08:58 UTC, lydiagray approved these changes

2022-03-08 08:58 UTC, merged